### ISSUE TITLE
2020-10-28: Using existing definitions

### ISSUE THREAD

**Issue by klbarnes20** [carpentries/glosario#166]
I was wondering if there is any precedent on using existing definitions and citing where they come from or if all definitions must be completely new and written based on your own knowledge.

**Comment by zkamvar** [comment]
I actually had the same question and was hesitant to add Korean translations because I was unsure of how to credit the source. 

@carpentries/glosario-maintainers, any thoughts?

**Comment by elletjies** [comment]
My immediate thought would be to cite existing definitions in a numbered style (i.e like Wikipedia).  Not sure how 'do-able' it is in Github and particularly the repo as it is now.

**Comment by gvwilson** [comment]
We could easily add a `sources` key with links and names. Should this be at the entry level or at the language level, i.e., would it be:

```
- slug: despondency
  sources:
  - name: "Wikipedia article on programming"
    url: http://something-or-other
  en:
    term: "depondency"
    def: "..."
  es:
    term: abatimiento
    def: "..."
```

or:

```
- slug: despondency
  en:
    term: "depondency"
    sources:
    - name: "Wikipedia article on programming"
      url: http://something-or-other
    def: "..."
  es:
    term: "abatimiento"
    # doesn't have external sources (yet)
    def: "..."
```
