### ISSUE TITLE
31 October 2020: Some glossary terms are overloaded terms (have other meanings in this context)

### ISSUE THREAD

**Issue by baileythegreen** [carpentries/glosario#171]
What is the appropriate way to address terms that have more than one meaning within the context represented by the scope of this glossary?

**Element**, for instance, is currently defined in relation to HTML/XML, but is also used to refer to the items inside of lists, sets, tuples, et cetera in different languages. Moreover, the definition for **empty_vector** currently reflects this second usage: 

> A vector that contains no elements. Empty vectors have a type such as logical or character, and are *not* the same as [null](#null).

What is the appropriate way to add multiple definitions? Can more than one `def: >` key be used per entry in the glossary?

This is not the only example where more than one meaning is possible, either.

**Comment by baileythegreen** [comment]
Is the model for the term `graph` what should be done?
```
 - slug: graph
  ref:
    - tree
  en:
    term: "graph"
    def: >
      1. A plot or a chart that displays data, or 2. a data structure in which
      [nodes](#node) are connected to one another by [edges](#edge).
```
