### ISSUE TITLE
2020-09-17: Markdown not processed in terms or cross-references

### ISSUE THREAD

**Issue by gvwilson** [carpentries/glosario#86]
Modify `glossary.yml` to use code font and italics in a term:

```
- slug: abandonware
  en:
    term: "`abandonware` *is great*"
    def: >
      Software that is no longer being maintained.
```

The formatting characters are shown literally, i.e., Markdown is not translated in term names.
